services:
  postgres:
    image: postgres:16
    container_name: postgres_dbt
    restart: always
    environment:
      POSTGRES_USER: ${dev_user}
      POSTGRES_PASSWORD: ${dev_password}
      POSTGRES_DB: ${dev_db_name}
    ports:
      - "5434:5432"
    volumes:
      - postgres_dbt_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${dev_user} -d ${dev_db_name}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_dbt_data: